#!/bin/bash

echo "🚀 Quick Database Fix for Time Tracking App"
echo ""

echo "You have two options:"
echo ""
echo "Option 1: Use Local Supabase (Recommended for Development)"
echo "=========================================================="
echo ""
echo "1. Make sure Docker is running"
echo "2. Run: supabase start"
echo "   (This will take 5-10 minutes on first run)"
echo "3. Run: supabase db push"
echo "4. Run: supabase gen types typescript --local > src/integrations/supabase/types.ts"
echo "5. Update your .env file to use local URL:"
echo "   VITE_SUPABASE_URL=http://localhost:54321"
echo "   VITE_SUPABASE_ANON_KEY=(get from 'supabase status' output)"
echo ""
echo ""
echo "Option 2: Use Remote Supabase (Your Current Setup)"
echo "==================================================="
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/dmsiccvhweqdpxbzbqig/editor"
echo "2. Click 'SQL Editor' in the left sidebar"
echo "3. Click 'New query'"
echo "4. Copy and paste each migration file in order:"
echo ""
echo "   a) supabase/migrations/20241111_initial_schema.sql"
echo "   b) supabase/migrations/20241111_per_project_architecture.sql"
echo "   c) supabase/migrations/20241111_api_keys.sql"
echo "   d) supabase/migrations/20241111_integrations.sql"
echo "   e) supabase/migrations/20241111_phase3_advanced_features.sql"
echo ""
echo "5. Click 'Run' for each migration"
echo "6. Generate types:"
echo "   supabase gen types typescript --linked > src/integrations/supabase/types.ts"
echo ""
echo ""
echo "Quick commands for Option 1:"
echo "=============================="
echo ""
echo "# Start Supabase (wait for it to finish)"
echo "supabase start"
echo ""
echo "# Push all migrations"
echo "supabase db push"
echo ""
echo "# Generate types"
echo "supabase gen types typescript --local > src/integrations/supabase/types.ts"
echo ""
echo "# Get your local credentials"
echo "supabase status"
echo ""
